window.CR_QUESTIONS=[];
const CR_DOMAINS=[
 ['transit agency','commuters','average commute time','express buses','road congestion'],['retailer','customers','monthly revenue','lower-priced bundles','competitor promotions'],['employer','employees','productivity','mentoring','self-selection'],['university','students','retention','weekly advising','prior preparation'],['health department','patients','clinic attendance','text reminders','distance to clinics'],['restaurant group','diners','table turnover','digital ordering','weekend demand'],['software company','customers','feature adoption','simplified onboarding','existing habits'],['library system','members','library visits','evening hours','neighborhood income'],['utility','households','electricity use','smart-meter alerts','home size'],['manufacturer','production lines','defect rate','automated inspection','supplier quality'],['farm cooperative','farms','crop yield','drip irrigation','soil quality'],['museum','visitors','repeat attendance','family workshops','tourist seasonality'],['education platform','learners','course completion','shorter lessons','learner motivation'],['housing authority','applicants','processing time','online forms','seasonal demand'],['service company','customers','resolution time','callback queues','case complexity'],['airport','passengers','security wait time','extra screening lanes','holiday traffic'],['sports academy','athletes','performance','video feedback','baseline ability'],['environmental agency','households','recycling rate','deposit incentives','collection access'],['bank','account holders','mobile-app usage','fee waivers','customer age'],['publisher','readers','ebook sales','lower digital prices','genre popularity'],['hotel chain','guests','guest satisfaction','mobile check-in','trip purpose'],['pharmacy chain','patients','pickup rate','SMS reminders','distance from stores'],['contractor','projects','project delays','prefabrication','weather disruptions'],['nonprofit','donors','donation revenue','monthly giving','donor income'],['conservation lab','artifacts','preservation','humidity controls','building age']
];
const CR_TYPES=['Strengthen','Weaken','Assumption','Inference','Evaluate','Conclusion','Flaw','Resolve Paradox','Bold Face','Method','Must Be True','Similar Reasoning','Complete the Passage'];
const CR_DIFF=['Easy','Medium','Hard'];
const cap=s=>s.charAt(0).toUpperCase()+s.slice(1);
function mkCR(i){
 const d=CR_DOMAINS[(i*7+Math.floor(i/13))%CR_DOMAINS.length],t=CR_TYPES[(i-1)%CR_TYPES.length],lv=CR_DIFF[Math.floor((i-1)/CR_TYPES.length)%3];
 const pct=5+(i*11)%26,n=18+(i*7)%67,place=['North','East','Central','West','South'][i%5],period=['one quarter','six months','one year','two semesters','three years'][i%5];
 const a=d[0],p=d[1],m=d[2],x=d[3],alt=d[4]; let s,q,c,o,e;
 const lead=`A ${a} has been considering whether ${x} can produce a sustained improvement in ${m}. The question became important after officials reviewed several locations and noticed that some ${p} associated with the program appeared to have better outcomes than ${p} who were not associated with it. Supporters of the proposal argue that the difference is evidence that the program itself is beneficial. Critics respond that the people, places, and circumstances involved were not necessarily comparable at the outset, and that factors such as ${alt} could have influenced the results. A review covering ${n} locations over ${period} found a difference of approximately ${pct}% in the reported measure. Because the organization must decide whether to expand the policy, it wants to determine what the evidence actually establishes rather than relying on an attractive but potentially misleading comparison.`;
 if(t==='Strengthen'){
  s=lead+` The officials therefore conclude that expanding ${x} to a broader population of ${p} is likely to improve ${m}, rather than merely being associated with it.`;
  q='Which of the following, if true, most strengthens the conclusion?';
  c=`A controlled pilot assigned otherwise comparable ${p} to receive ${x} or not receive it, and the group receiving the intervention showed a similar improvement in ${m} while the comparison group did not.`;
  o=[`Some ${p} said that they were already familiar with the program.`,`The ${x} program requires several employees to receive additional training.`,`The largest improvement was recorded at a ${place} location.`,`Several ${p} preferred a different policy that was not tested.`];
  e='The controlled comparison reduces the main alternative explanation: that people who received the intervention were already different. Reproducing the improvement under comparable conditions provides stronger evidence that the intervention itself contributes to the outcome.';
 } else if(t==='Weaken'){
  s=lead+` On the basis of this review, the organization concludes that ${x} caused the improvement in ${m} and therefore recommends making the program standard for all ${p}.`;
  q='Which of the following, if true, most weakens the conclusion?';
  c=`The ${p} who chose ${x} were disproportionately people who already had characteristics that independently tend to produce better ${m}.`;
  o=[`The review included ${n} locations from several regions.`,`The organization has used ${x} for ${period}.`,`Some ${p} reported being satisfied with the program.`,`The difference was especially noticeable at ${place} locations.`];
  e='If the people who selected the intervention were already more likely to achieve better outcomes, their success could explain the observed difference. That makes the conclusion that the intervention caused the improvement substantially weaker.';
 } else if(t==='Assumption'){
  s=lead+` The organization argues that the observed difference provides sufficient reason to expand ${x}, because it believes that the intervention is responsible for the better ${m} among the participating ${p}.`;
  q='The argument depends on which of the following assumptions?';
  c=`The difference in ${m} is not primarily explained by pre-existing differences between ${p} who received ${x} and ${p} who did not.`;
  o=[`Most ${p} have heard of the program.`,`The program can be administered at ${place} locations.`,`The intervention has received favorable publicity.`,`Some ${p} prefer traditional methods.`];
  e='The conclusion treats the observed difference as evidence of an effect. Therefore it must assume that another pre-existing difference did not cause the outcome; otherwise the evidence would not justify the conclusion.';
 } else if(t==='Inference'||t==='Must Be True'){
  s=`A ${a} has established a policy governing ${p} who use ${x}. Under the policy, every person who receives a particular benefit must satisfy a stated eligibility requirement. Records for ${period} show that every recipient of the benefit satisfied that requirement. The records also show that some ${p} who were eligible did not use ${x}, and no record indicates that an ineligible person received the benefit. Officials emphasize that the records concern actual recipients rather than everyone who was eligible, and that the existence of eligibility does not by itself imply that a person used the program or received the benefit. The policy has remained unchanged during the period covered by the records.`;
  q='Which of the following must be true?';
  c=`No person who received the benefit while using ${x} was ineligible under the stated requirement.`;
  o=[`Everyone who was eligible used ${x}.`,`Everyone in ${place} received the benefit.`,`The benefit was available only to people who used ${x}.`,`The stated requirement was the only condition for receiving the benefit.`];
  e='The passage explicitly states that every recipient satisfied the requirement. The other choices make stronger claims about all eligible people, all locations, or additional policy conditions that the passage does not establish.';
 } else if(t==='Evaluate'){
  s=`A ${a} is considering a proposal to expand ${x}. Supporters point to earlier observations showing that ${p} associated with the intervention had better ${m}. The observations covered several locations and appeared consistent enough to attract attention from senior officials. Critics, however, note that participation was not necessarily random and that the earlier ${p} may differ from the larger population that would be affected by the proposed expansion. In particular, the critics worry that the apparent benefit could depend on ${alt}, or on other characteristics that were more common among participants in the original study. Before approving the proposal, the decision makers want evidence that would distinguish a genuine effect from a difference caused by the composition of the groups.`;
  q='Which of the following questions would be most useful in evaluating the prediction made by the proposal?';
  c=`Are the ${p} expected to receive ${x} in the proposed expansion substantially different from those whose outcomes produced the original evidence?`;
  o=[`How long has the organization offered services to ${p}?`,`How many employees would be assigned to administer ${x}?`,`What format would be used to explain the policy to ${p}?`,`How many neighboring organizations have heard about the proposal?`];
  e='The key issue is generalization. If the new population differs in a way that affects the outcome, the earlier result may not predict what will happen after expansion. The other questions do not directly test that issue.';
 } else if(t==='Conclusion'){
  s=`A survey conducted by a ${a} found that ${pct}% of ${p} who used ${x} reported improved ${m}. Among otherwise comparable ${p} who did not use the intervention, only ${Math.max(1,pct-10)}% reported such an improvement. The survey covered several locations over ${period}, and the difference was large enough for the organization to consider changing its policy. The researchers caution, however, that participants were not randomly assigned to the two groups. They also found that the groups differed somewhat in ${alt}. The organization nevertheless wants to use the survey when deciding whether to recommend ${x} more widely, while avoiding a conclusion stronger than the evidence warrants.`;
  q='Which conclusion is best supported by the information above?';
  c=`There is an association between ${x} and reported ${m}, but the survey alone does not establish that ${x} caused the difference.`;
  o=[`${cap(x)} definitely causes better ${m}.`,`${cap(x)} has no effect whatsoever on ${m}.`,`All ${p} should immediately be required to use ${x}.`,`The two groups were proven identical before the survey.`];
  e='The survey shows a relationship between the intervention and the reported outcome, but the lack of random assignment and the difference in another relevant factor leave alternative explanations open. Therefore causation is not established.';
 } else if(t==='Flaw'){
  s=`A ${a} observes that ${p} in ${place} who adopted ${x} achieved better ${m} than ${p} who did not. The report acknowledges that adoption was voluntary, that the two groups were not matched on every relevant characteristic, and that ${alt} varied considerably across locations. Nevertheless, the ${a} concludes that requiring all ${p} to adopt ${x} will produce the same improvement. It argues that because the successful group used the intervention, the intervention must have been responsible for the outcome. The report then treats the observed difference as sufficient reason to impose the policy throughout the organization.`;
  q='The reasoning is most vulnerable to which of the following criticisms?';
  c='It treats an association involving a self-selected group as sufficient evidence that imposing the intervention will cause the observed outcome.';
  o=['It rejects the conclusion solely because the intervention is unfamiliar.','It assumes that every observed trend must eventually disappear.','It confuses a necessary condition with an average result without discussing either.','It relies on a definition that directly contradicts the evidence presented.'];
  e='The argument moves from correlation to causation. Because participation was voluntary and the groups differed in other respects, the better outcome could have resulted from those differences rather than from the intervention.';
 } else if(t==='Resolve Paradox'){
  s=`A report from a ${a} found that ${p} who received ${x} experienced a ${pct}% improvement in ${m}. Yet the organization reported that its overall measure of ${m} declined during the same ${period}. At first the two findings seem inconsistent: if the intervention improved the outcome for the people who received it, one might expect the organization-wide measure to improve as well. Managers examined the records and confirmed that neither result was a reporting error. They therefore want to identify a circumstance that could make both findings true at the same time, without rejecting the reported improvement among participants or the reported decline in the overall population.`;
  q='Which of the following, if true, best explains the apparent discrepancy?';
  c=`The ${p} receiving ${x} represented only a small subgroup, while a much larger group experienced a decline in ${m} for an unrelated reason.`;
  o=[`The ${x} program received favorable publicity from local officials.`,`Some participants said that they were satisfied with the intervention.`,`The organization tracked ${m} more frequently than it had in previous years.`,`The intervention was discussed at a meeting attended by senior managers.`];
  e='A subgroup can improve while the overall population declines if the subgroup is small and a much larger group worsens enough to outweigh its improvement. Thus both reported findings can be true simultaneously.';
 } else if(t==='Bold Face'){
  s=`A ${a} reports that ${x} was associated with better ${m} across several locations. **However,** ${alt} varied substantially among those locations, making it difficult to determine whether the observed difference was caused by the intervention or by other conditions. **Therefore,** the report recommends a randomized trial before concluding that ${x} caused the improvement. The authors explain that the proposed trial would create a more informative comparison and would give officials a stronger basis for deciding whether the policy should be expanded. They emphasize that the existing observations are useful but do not by themselves settle the causal question.`;
  q='The two boldfaced portions play which of the following roles?';
  c='The first presents evidence relevant to a causal claim; the second identifies a limitation of that evidence and motivates a stronger test.';
  o=['The first states the final conclusion; the second provides unrelated background information.','The first gives a definition of the intervention; the second proves that definition false.','The first presents an objection to the policy; the second demonstrates that the objection is irrelevant.','The first gives a recommendation for implementation; the second proves that implementation has succeeded.'];
  e='The first bold portion supplies an observation that could support a causal claim. The second acknowledges that an alternative explanation remains and proposes a method for resolving that uncertainty.';
 } else if(t==='Method'){
  s=`A ${a} initially compared ${m} among ${p} who had chosen ${x} with ${m} among ${p} who had not. The researchers found a noticeable difference, but they recognized that people who voluntarily chose the intervention might differ from those who did not. To address this concern, they conducted a separate study in which otherwise comparable participants were assigned to receive or not receive the intervention. They then checked whether the original pattern appeared again. The researchers reasoned that if the difference persisted under the second design, the possibility that the original result was caused only by differences among the people who selected the intervention would be reduced.`;
  q='The argument’s method is best described as';
  c='checking whether an initially observed association persists when selection differences are reduced through a separate comparison.';
  o=['replacing quantitative evidence with an appeal to authority.','assuming that correlation automatically proves causation.','using an anecdote to reject an otherwise consistent trend.','inferring a universal rule from one unusual case.'];
  e='The second study is designed to reduce the main alternative explanation for the first result: that the people who selected the intervention were systematically different. Reproducing the pattern under more controlled conditions strengthens the causal interpretation.';
 } else if(t==='Similar Reasoning'){
  s=`A ${a} argues that a small pilot of ${x} produced better ${m} at one location. The pilot location had unusual circumstances, and the report admits that other locations may differ in important ways. Nevertheless, the report says that the pilot was successful and therefore concludes that every ${p} should adopt the intervention immediately. No evidence is presented showing that the other locations are comparable to the pilot location. The recommendation thus depends on extending a result obtained in one setting to a much broader set of settings without first establishing that the relevant circumstances are sufficiently similar.`;
  q='Which of the following arguments most closely parallels the reasoning above?';
  c='A trial of a new scheduling system worked at one branch, so every branch should adopt it without testing whether circumstances at the branches are comparable.';
  o=['A cheaper product should be preferred when its quality is equal to that of a more expensive product.','A rule applies to all employees, so it should be enforced consistently.','A measurement was repeated twice, so its average is likely to be more reliable.','A proposal has benefits and costs, so decision makers should compare both before acting.'];
  e='Both arguments generalize from a favorable result in one setting to a much broader population without establishing that the relevant circumstances are comparable.';
 } else {
  s=`A study by a ${a} found that ${p} using ${x} had better ${m}. The researchers caution that the study did not randomly assign participants to the two groups and that ${alt} differed between them. As a result, the study demonstrates an association but does not by itself demonstrate causation. The organization wants to learn whether the intervention itself produces the observed benefit, because a decision to expand the program would affect a much larger number of ${p}. The researchers therefore argue that the next investigation should address the central weakness of the original comparison rather than simply collecting more observations of the same kind.`;
  q='Which option most logically completes the passage?';
  c=`compare otherwise similar ${p} while controlling for or accounting for differences in ${alt}`;
  o=['use a larger font in the final report',`exclude all ${p} who did not use ${x}`,'assume the observed association is causal',`avoid measuring ${m} in future studies`];
  e='The proposed step addresses the key limitation of the original study by making the comparison groups more similar on a factor that could otherwise explain the result. More observations of the same uncontrolled comparison would not solve that problem.';
 }
 let opts=[c,...o],k=(i*3)%5; opts=opts.slice(k).concat(opts.slice(0,k)); const answer=(5-k)%5;
 return {id:i,type:t,difficulty:lv,stimulus:s,question:q,options:opts,answer,explanation:e};
}
for(let i=1;i<=1953;i++)CR_QUESTIONS.push(mkCR(i));
const CR_SOURCES=['GMAT-STYLE ORIGINAL','LSAT-STYLE ORIGINAL','ORIGINAL CR BANK'];
window.CR_DATA={questions:CR_QUESTIONS,sets:Array.from({length:196},(_,j)=>{let start=j*10+1,end=Math.min(start+9,1953);return{id:j+1,name:String(j+1).padStart(3,'0'),source:CR_SOURCES[j%3],question_ids:Array.from({length:end-start+1},(_,k)=>start+k)}})};
